from myapp.models import Product
Product.objects.all().delete()

data  = [
    {"id": 1, "image": "images/61kVeIFOnFL._AC_SX466_.jpg", "name": "High-End Laptop", "description": "Powerful performance and sleek design for professionals.", "brand": "Brand: Lenovo", "price": 1249.99, "category": "Laptop", "features": ["32GB RAM DDR5", "1TB SSD", "Intel i7-1355U Processor", "16 inch Display", "Win 11 pro"]},
    {"id": 2, "image": "images/Latest Smartphone.jpg", "name": "Samsung S24 Ultra", "description": "Stay connected with style and cutting-edge features.", "brand": "Brand: Samsung", "price": 1299.99, "category": "Mobile", "features": ["6.5 inch OLED Display", "128GB Storage", "Triple Camera System", "5G Connectivity"], "model3D": "images/samsung_s24_ultra.glb"},
    {"id": 3, "image": "images/Wireless Headphones.jpg", "name": "Wireless Headphones", "description": "Experience sound quality like never before.", "brand": "Brand: Sony", "price": 119.99, "category": "Computer Accessories", "features": ["Active Noise Cancellation", "30 Hours Battery Life", "Touch Controls", "Fast Charging"]},
    {"id": 4, "image": "images/Smartwatch.jpg", "name": "Smartwatch", "description": "Track your health and fitness in style.", "brand": "Brand: Apple", "price": 199.99, "category": "Smartwatch", "features": ["Heart Rate Monitor", "Sleep Tracking", "GPS Navigation", "7 Days Battery Life"]},
    {"id": 5, "image": "images/Bluetooth Speaker.jpg", "name": "Bluetooth Speaker", "description": "Portable speaker with immersive sound.", "brand": "Brand: JBL", "price": 79.99, "category": "Audio", "features": ["360° Surround Sound", "Waterproof Design", "12 Hours Playtime", "Hands-Free Calls"]},
    {"id": 6, "image": "images/Gaming Monitor.jpg", "name": "Gaming Monitor", "description": "Ultra-smooth visuals for serious gamers.", "brand": "Brand: ASUS", "price": 349.99, "category": "Laptop", "features": ["27-inch QHD Display", "165Hz Refresh Rate", "G-Sync Compatible", "HDR Support"]},
    {"id": 7, "image": "images/Mechanical Keyboard.jpg", "name": "Mechanical Keyboard", "description": "Tactile typing experience with RGB lighting.", "brand": "Brand: Logitech", "price": 99.99, "category": "Computer Accessories", "features": ["Hot-Swappable Keys", "Customizable RGB", "Durable Build", "USB-C Connectivity"]},
    {"id": 8, "image": "images/Wireless Mouse.jpg", "name": "Wireless Mouse", "description": "Lightweight and precise for everyday use.", "brand": "Brand: HP", "price": 49.99, "category": "Computer Accessories", "features": ["Ergonomic Design", "Adjustable DPI", "Rechargeable Battery", "Bluetooth & USB Support"]},
    {"id": 9, "image": "images/4K Smart TV.jpg", "name": "4K Smart TV", "description": "Stunning visuals and advanced streaming options.", "brand": "Brand: LG", "price": 799.99, "category": "TV", "features": ["55-inch Ultra HD", "HDR10+ Support", "Built-in Streaming Apps", "Voice Control"]},
    {"id": 10, "image": "images/Drone with Camera.jpg", "name": "Drone with Camera", "description": "Capture aerial shots with precision.", "brand": "Brand: DJI", "price": 699.99, "category": "Camera", "features": ["4K Camera", "30-Minute Flight Time", "Obstacle Detection", "Mobile App Control"]},
    {"id": 11, "image": "images/Gaming Headset.jpg", "name": "Gaming Headset", "description": "Immerse yourself in your games with 3D audio.", "brand": "Brand: Razer", "price": 79.99, "category": "Audio", "features": ["Surround Sound", "Noise-Canceling Mic", "LED Lighting", "Memory Foam Ear Cushions"]},
    {"id": 12, "image": "images/Action Camera.jpg", "name": "Action Camera", "description": "Rugged and ready for any adventure.", "brand": "Brand: GoPro", "price": 249.99, "category": "Camera", "features": ["4K Video Recording", "Waterproof Design", "Wide-Angle Lens", "Wi-Fi Sharing"]},
    {"id": 13, "image": "images/External Hard Drive.jpg", "name": "External Hard Drive", "description": "Securely store your files and backups.", "brand": "Brand: Seagate", "price": 99.99, "category": "Computer Accessories", "features": ["2TB Storage", "USB 3.0 Interface", "Shockproof Design", "Auto Backup"]},
    {"id": 14, "image": "images/Smart Home Hub.jpg", "name": "Smart Home Hub", "description": "Control your smart devices effortlessly.", "brand": "Brand: Google", "price": 129.99, "category": "Home Appliance", "features": ["Voice Assistant Integration", "Multi-Room Audio", "Compact Design", "Wi-Fi and Bluetooth"]},
    {"id": 15, "image": "images/VR Headset.jpg", "name": "VR Headset", "description": "Step into a whole new reality.", "brand": "Brand: Oculus", "price": 399.99, "category": "Mobile", "features": ["High-Resolution Display", "Motion Tracking", "Lightweight Design", "Wide Content Library"]},
    {"id": 16, "image": "images/Robot Vacuum.jpg", "name": "Robot Vacuum", "description": "Clean your home effortlessly.", "brand": "Brand: iRobot", "price": 299.99, "category": "Home Appliance", "features": ["Smart Mapping", "App Control", "Auto-Charging", "Pet Hair-Friendly"]},
    {"id": 17, "image": "images/Portable Projector.jpg", "name": "Portable Projector", "description": "Bring the theater experience anywhere.", "brand": "Brand: Anker", "price": 249.99, "category": "Laptop", "features": ["1080p Resolution", "Wi-Fi Connectivity", "Compact Design", "Built-in Speakers"]},
    {"id": 18, "image": "images/Smart Thermostat.jpg", "name": "Smart Thermostat", "description": "Efficiently control your home's temperature.", "brand": "Brand: Nest", "price": 149.99, "category": "Home Appliance", "features": ["Energy Saving", "Voice Control", "Mobile App Integration", "Sleek Design"]},
    {"id": 19, "image": "images/Noise-Canceling Earbuds.jpg", "name": "Noise-Canceling Earbuds", "description": "Compact and powerful sound experience.", "brand": "Brand: Bose", "price": 129.99, "category": "Audio", "features": ["Active Noise Canceling", "Wireless Charging Case", "8-Hour Battery Life", "Touch Controls"]},
    {"id": 20, "image": "images/Electric Scooter.jpg", "name": "Electric Scooter", "description": "Eco-friendly and convenient city travel.", "brand": "Brand: Segway", "price": 499.99, "category": "Mobile", "features": ["Max Speed 25 km/h", "Foldable Design", "LED Display", "30 km Range"]},
    {"id": 21, "image": "images/Portable Power Bank.jpg", "name": "Portable Power Bank", "description": "Stay charged wherever you go.", "brand": "Brand: Anker", "price": 49.99, "category": "Power Bank", "features": ["20,000mAh Capacity", "Fast Charging", "Dual USB Output", "Compact Design"]},
    {"id": 22, "image": "images/Streaming Webcam.jpg", "name": "Streaming Webcam", "description": "Crystal-clear video for content creators.", "brand": "Brand: Logitech", "price": 99.99, "category": "Computer Accessories", "features": ["1080p HD Video", "Auto-Focus", "Built-in Microphone", "Low-Light Correction"]},
    {"id": 23, "image": "images/Smart Light Bulbs.jpg", "name": "Smart Light Bulbs", "description": "Control your lighting with ease.", "brand": "Brand: Philips Hue", "price": 29.99, "category": "Home Appliance", "features": ["Color Changing", "Voice Control", "Energy Efficient", "App Control"]},
    {"id": 24, "image": "images/ps5.webp", "name": "PlayStation 5", "description": "The PlayStation 5 is Sony's next-generation gaming console, offering immersive gaming experiences with stunning visuals and lightning-fast performance. Equipped with a powerful 1TB SSD and a built-in disc drive, the PS5 ensures quick load times and the ability to play both digital and physical games. This bundle includes essential accessories like the DualSense Wireless Controller, horizontal stand feet, an HDMI cable, AC power cord, USB cable, and printed materials to get you started.", "brand": "Brand: Sony", "price": 430.97, "category": "PlayStation", "features": ["Includes DualSense Wireless Controller", "1TB SSD, Disc Drive", "2 Horizontal Stand Feet", "HDMI Cable, AC power cord", "USB cable", "Printed materials"]},
    {"id": 25, "image": "images/Apple_Smartphone.jpg", "name": "Apple iPhone 16 Pro Max", "description": "Experience premium quality and seamless performance with the latest Apple Smartphone.", "brand": "Brand: Apple", "price": 1389.94, "category": "Mobile", "model3D": "images/iphone_16_pro_Max.glb", "features": ["Premium Quality", "Seamless Performance", "High-resolution Display", "5G Connectivity"]},
    {"id": 26, "image": "images/Huawei_Laptop.png", "name": "Huawei MateBook E Go", "description": "120 Hz Eye Comfort HUAWEI FullView Display | Sleek Design and Long Battery Life | 2-in-1 Laptop", "brand": "Brand: Huawei", "price": 857.19, "category": "Laptop", "features": ["120 Hz Display", "Sleek Design", "2-in-1 Functionality", "Long Battery Life"]},
    {"id": 27, "image": "images/Midea_AirConditioner.jpeg", "name": "Midea Split Air Conditioner", "description": "Create pure comfort with class leading air conditioning technology for rooms 16-23m²*. Now you have the choice of next generation, eco friendly and energy efficient R32 refrigerant for your split system air conditioner.", "brand": "Brand: Midea", "price": 850.49, "category": "Home Appliance", "features": ["3.5kW Apollo Series", "Follow me: Air conditioner will follow the remote controller to cool the room.", "3D airflow: Directional air - outlet moves automatically both horizontally and vertically, directing nice and cool airflow to cover every corner of the room.", "Timer: Timer can be set to start and stop at any point in a 24 hour period."]},
    {"id": 28, "image": "images/Panasonic_Television.png", "name": "Panasonic Television", "description": "The flagship Mini 4K Smart LED NX950 TV, which features our new Flat Fit design, is capable of delivering maximum picture and sound quality while freeing up your physical space. A seamless fit for all of your favorite programs, games, and events.", "brand": "Brand: Panasonic", "price": 2294.99, "category": "TV", "features": ["Operating System: Google TV", "Resolution: 3,840 x 2,160", "Processor: 4K Studio Colour Engine", "Type: Mini LED", "Refresh Rate: 120Hz", "Surround: 360° Soundscape", "HDMI: 4, USB: 2"]},
    {"id": 29, "image": "images/Xiaomi_Smartwatch.png", "name": "Xiaomi Watch S3", "description": "Stay connected with style and cutting-edge features at an affordable price.", "brand": "Brand: Xiaomi", "price": 199.99, "category": "Smartwatch", "features": ["Heart Rate Monitor", "Water Resistant", "GPS Tracking", "Affordable Price"]},
    {"id": 30, "image": "images/Dell_Desktop.png", "name": "Dell Desktop Computer", "description": "High-performance computing for productivity and gaming.", "brand": "Brand: Dell", "price": 799.99, "category": "Laptop", "features": ["Windows 11 Pro", "CPU Model: Core i5", "CPU Speed: 3 GHz", "Memory Storage Capacity: 32 GB"]},
    {"id": 31, "image": "images/Lenovo_Tablet.png", "name": "Lenovo Tab M8 FHD", "description": "Portable and powerful tablet for work and entertainment.", "brand": "Brand: Lenovo", "price": 349.99, "category": "Mobile", "features": ["Android™ 9 Pie™", "8″ FHD (1920 x 1200) IPS, 350nits, 10-point multi-touch", "3GB RAM", "32GB ROM", "Up to 2TB exFAT or 128GB FAT32 microSD card support", "5100mAh (Typical)"]},
    {"id": 32, "image": "images/Canon_Camera.png", "name": "Canon EOS R5 Mark II", "description": "Capture stunning images with precision and clarity.", "brand": "Brand: Canon", "price": 3388.96, "category": "Mobile", "features": ["High-resolution Sensor", "Image Stabilization", "Fast Autofocus", "Professional Mode"]},
    {"id": 33, "image": "images/Haier_Refrigerator.png", "name": "Haier Refrigerator", "description": "Innovative cooling technology for your fresh food storage needs.", "brand": "Brand: Haier", "price": 1239.99, "category": "Home Appliance", "features": ["Multi-Zone Cooling", "Energy Efficient", "Smart Control", "Spacious Interior"]},
    {"id": 34, "image": "images/Intal_i9.png", "name": "Intel i9 14900K", "description": "New Intel® Core™ i9 14900K 24-Core 8P+16E Gaming Desktop Processor with Integrated Graphics Unlocked, LGA 771", "brand": "Brand: Intel", "price": 459.99, "category": "PC Components", "features": ["24 cores (8 P-cores + 16 E-cores)", "4.4 GHz", "LGA 1700", "High-quality material"]},
]

for product in data:
    features = product.get("features", [])
    cleaned_data = ", ".join(features)  # Convert list to a comma-separated string
    Product.objects.create(
        name=product["name"],
        description=product["description"],
        brand=product["brand"],
        price=product["price"],
        image=product["image"],
        category=product["category"],
        features=cleaned_data,
        model3D=product.get("model3D", None)
    )

print("Products added successfully!")

